-- Drop existing table if it exists
drop table if exists messages;

-- Create messages table with correct schema
create table messages (
  id bigint generated by default as identity primary key,
  content text,
  author text not null,
  image_url text,
  merzh_width integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for faster queries
create index messages_created_at_idx on messages(created_at desc);

-- Set up RLS (Row Level Security)
alter table messages enable row level security;

-- Create policy to allow all operations (since this is a public board)
create policy "Allow all operations for all users" on messages
  for all
  using (true)
  with check (true); 